// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeaponsOfOrder.Infrastructure.Persistence;

#nullable disable

namespace WeaponsOfOrder.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WeaponsOfOrderDbContext))]
    partial class WeaponsOfOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.ArmyPlacement", b =>
                {
                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerUnitId")
                        .HasColumnType("uuid");

                    b.Property<int?>("HexColumn")
                        .HasColumnType("integer");

                    b.Property<int?>("HexRow")
                        .HasColumnType("integer");

                    b.Property<int?>("ReserveOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OwnerUserId", "PlayerUnitId");

                    b.HasIndex("OwnerUserId", "ReserveOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_ArmyPlacements_OwnerUserId_ReserveOrder")
                        .HasFilter("\"Role\" = 'Reserve'");

                    b.HasIndex("PlayerUnitId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "HexColumn", "HexRow")
                        .IsUnique()
                        .HasDatabaseName("IX_ArmyPlacements_OwnerUserId_Hex")
                        .HasFilter("\"Role\" = 'Active'");

                    b.ToTable("ArmyPlacements", t =>
                        {
                            t.HasCheckConstraint("CK_ArmyPlacements_OwnHalf", "\"HexColumn\" IS NULL\nOR (\"HexColumn\" >= 0 AND \"HexColumn\" < 4\n    AND \"HexRow\" >= 0 AND \"HexRow\" < 7)");

                            t.HasCheckConstraint("CK_ArmyPlacements_ReserveOrder", "\"ReserveOrder\" IS NULL OR \"ReserveOrder\" >= 0");

                            t.HasCheckConstraint("CK_ArmyPlacements_RoleShape", "(\"Role\" = 'Active' AND \"HexColumn\" IS NOT NULL AND \"HexRow\" IS NOT NULL AND \"ReserveOrder\" IS NULL)\nOR (\"Role\" = 'Reserve' AND \"HexColumn\" IS NULL AND \"HexRow\" IS NULL AND \"ReserveOrder\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.EquippedWeapon", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EquippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OccupiesFirstSlot")
                        .HasColumnType("boolean");

                    b.Property<bool>("OccupiesSecondSlot")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ItemId", "OwnerUserId")
                        .IsUnique();

                    b.HasIndex("PlayerUnitId", "OwnerUserId");

                    b.HasIndex(new[] { "PlayerUnitId" }, "FirstSlotOccupant")
                        .IsUnique()
                        .HasDatabaseName("IX_EquippedWeapons_PlayerUnitId_FirstSlot")
                        .HasFilter("\"OccupiesFirstSlot\"");

                    b.HasIndex(new[] { "PlayerUnitId" }, "SecondSlotOccupant")
                        .IsUnique()
                        .HasDatabaseName("IX_EquippedWeapons_PlayerUnitId_SecondSlot")
                        .HasFilter("\"OccupiesSecondSlot\"");

                    b.ToTable("EquippedWeapons", t =>
                        {
                            t.HasCheckConstraint("CK_EquippedWeapons_OccupiesASlot", "\"OccupiesFirstSlot\" OR \"OccupiesSecondSlot\"");
                        });
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.ForgeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BurnSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Craftsmanship")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHeating")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastStrikeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("StrikesTaken")
                        .HasColumnType("integer");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("TemperatureAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ForgeSessions_OwnerUserId_Active")
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("OwnerUserId", "StartedAt");

                    b.ToTable("ForgeSessions");
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.ForgeStrike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ForgeSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StruckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ForgeSessionId", "Ordinal")
                        .IsUnique();

                    b.ToTable("ForgeStrikes");
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.ForgedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Craftsmanship")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ForgeSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ForgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ForgeSessionId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "ForgedAt");

                    b.ToTable("ForgedItems");
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.PlayerMaterials", b =>
                {
                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Leather")
                        .HasColumnType("integer");

                    b.Property<int>("Metal")
                        .HasColumnType("integer");

                    b.Property<int>("Wood")
                        .HasColumnType("integer");

                    b.HasKey("OwnerUserId");

                    b.ToTable("PlayerMaterials", t =>
                        {
                            t.HasCheckConstraint("CK_PlayerMaterials_NonNegative", "\"Metal\" >= 0 AND \"Wood\" >= 0 AND \"Leather\" >= 0");
                        });
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.PlayerUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("StarterGrantKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "AcquiredAt");

                    b.HasIndex("OwnerUserId", "StarterGrantKey")
                        .IsUnique()
                        .HasDatabaseName("IX_PlayerUnits_OwnerUserId_StarterGrantKey")
                        .HasFilter("\"StarterGrantKey\" IS NOT NULL");

                    b.ToTable("PlayerUnits");
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Identity.WeaponsOfOrderUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("WeaponsOfOrder.Infrastructure.Identity.WeaponsOfOrderUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("WeaponsOfOrder.Infrastructure.Identity.WeaponsOfOrderUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("WeaponsOfOrder.Infrastructure.Identity.WeaponsOfOrderUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.ArmyPlacement", b =>
                {
                    b.HasOne("WeaponsOfOrder.Infrastructure.Gameplay.PlayerUnit", null)
                        .WithMany()
                        .HasForeignKey("PlayerUnitId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.EquippedWeapon", b =>
                {
                    b.HasOne("WeaponsOfOrder.Infrastructure.Gameplay.ForgedItem", null)
                        .WithOne()
                        .HasForeignKey("WeaponsOfOrder.Infrastructure.Gameplay.EquippedWeapon", "ItemId", "OwnerUserId")
                        .HasPrincipalKey("WeaponsOfOrder.Infrastructure.Gameplay.ForgedItem", "Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeaponsOfOrder.Infrastructure.Gameplay.PlayerUnit", null)
                        .WithMany()
                        .HasForeignKey("PlayerUnitId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.ForgeSession", b =>
                {
                    b.HasOne("WeaponsOfOrder.Infrastructure.Identity.WeaponsOfOrderUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.ForgeStrike", b =>
                {
                    b.HasOne("WeaponsOfOrder.Infrastructure.Gameplay.ForgeSession", "Session")
                        .WithMany("Strikes")
                        .HasForeignKey("ForgeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.ForgedItem", b =>
                {
                    b.HasOne("WeaponsOfOrder.Infrastructure.Gameplay.ForgeSession", null)
                        .WithOne()
                        .HasForeignKey("WeaponsOfOrder.Infrastructure.Gameplay.ForgedItem", "ForgeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeaponsOfOrder.Infrastructure.Identity.WeaponsOfOrderUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.PlayerMaterials", b =>
                {
                    b.HasOne("WeaponsOfOrder.Infrastructure.Identity.WeaponsOfOrderUser", null)
                        .WithOne()
                        .HasForeignKey("WeaponsOfOrder.Infrastructure.Gameplay.PlayerMaterials", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.PlayerUnit", b =>
                {
                    b.HasOne("WeaponsOfOrder.Infrastructure.Identity.WeaponsOfOrderUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponsOfOrder.Infrastructure.Gameplay.ForgeSession", b =>
                {
                    b.Navigation("Strikes");
                });
#pragma warning restore 612, 618
        }
    }
}
