<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>WeaponsOfOrder.Api.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WeaponsOfOrder.Api\WeaponsOfOrder.Api.csproj" />
  </ItemGroup>

</Project>
